/**
 * 弓の一覧（**48 本**）。
 *
 * 仕様は `docs/spec/19-weapons.md`。
 *
 * > ### このファイルは書き出したもの。**手で直さない。**
 * >
 * > 出どころは `tools/pve_weapon_table.py`。
 * > **直したらもう一度走らせる**（`python tools/pve-weapons-code.py`）。
 *
 * **ここにあるのはデータだけ。** 何が起きるかは `features/bow/abilities/`
 *（`docs/spec/11-structure.md` 2-1）。
 */

import type { Bow } from "./weapons.js";

export const BOW_LIST: readonly Bow[] = [
  {
    item: "pve:bow_common",
    label: "支給された弓",
    rarity: "common",
    base: 30,
    ability: "none",
    trail: "pve:trail_common",
    trailSound: "pve.trail.common",
  },
  {
    item: "pve:bow_heal",
    label: "癒しの弓",
    rarity: "uncommon",
    base: 50,
    ability: "heal_ally",
    effect: "癒しの弓",
    about: "味方に当てると回復（最終攻撃力に依存）",
    trail: "pve:trail_heal",
    trailSound: "pve.trail.heal",
    abilitySound: "pve.ability.heal",
  },
  {
    item: "pve:bow_rapid",
    label: "速射弓",
    rarity: "uncommon",
    base: 25,
    fullTicks: 1,
    ability: "rapid",
    effect: "速射弓",
    about: "ためが無い。1 発は 1/10、0.05 秒ごとに撃てる",
    trail: "pve:trail_rapid",
    trailSound: "pve.trail.rapid",
    abilitySound: "pve.ability.rapid",
  },
  {
    item: "pve:bow_long",
    label: "長弓",
    rarity: "uncommon",
    base: 64,
    fullTicks: 40,
    ability: "long_draw",
    effect: "長弓",
    about: "ためを 2 秒まで延ばせる（1.6 倍）",
    trail: "pve:trail_long",
    trailSound: "pve.trail.long",
    abilitySound: "pve.ability.long",
  },
  {
    item: "pve:bow_scatter",
    label: "散華",
    rarity: "uncommon",
    base: 38,
    ability: "spread3",
    effect: "散華",
    about: "3 本に散らす（各 70%）",
    trail: "pve:trail_scatter",
    trailSound: "pve.trail.scatter",
    abilitySound: "pve.ability.scatter",
  },
  {
    item: "pve:bow_stake",
    label: "杭打ち弓",
    rarity: "uncommon",
    base: 50,
    ability: "knock_far",
    effect: "杭打ち弓",
    about: "大きく吹き飛ばす",
    trail: "pve:trail_stake",
    trailSound: "pve.trail.stake",
    abilitySound: "pve.ability.stake",
  },
  {
    item: "pve:bow_heavy",
    label: "重弓",
    rarity: "uncommon",
    base: 52,
    fullTicks: 30,
    ability: "heavy_draw",
    effect: "重弓",
    about: "ため 1.5 秒で 1.5 倍",
    trail: "pve:trail_heavy",
    trailSound: "pve.trail.heavy",
    abilitySound: "pve.ability.heavy",
  },
  {
    item: "pve:bow_chain",
    label: "鎖弓",
    rarity: "uncommon",
    base: 50,
    ability: "chain_mark",
    effect: "鎖弓",
    about: "当てた敵に鎖。次の 1 発は必ず当たる",
    trail: "pve:trail_chain",
    trailSound: "pve.trail.chain",
    abilitySound: "pve.ability.chain",
  },
  {
    item: "pve:bow_recoil",
    label: "反動弓",
    rarity: "uncommon",
    base: 50,
    ability: "recoil",
    effect: "反動弓",
    about: "撃つと自分が後ろへ跳ぶ",
    trail: "pve:trail_recoil",
    trailSound: "pve.trail.recoil",
    abilitySound: "pve.ability.recoil",
  },
  {
    item: "pve:bow_purify",
    label: "破魔矢",
    rarity: "uncommon",
    base: 50,
    ability: "element_boost",
    effect: "破魔矢",
    about: "属性の蓄積が 2 倍",
    trail: "pve:trail_purify",
    trailSound: "pve.trail.purify",
    abilitySound: "pve.ability.purify",
  },
  {
    item: "pve:bow_hunter",
    label: "狩人の弓",
    rarity: "uncommon",
    base: 50,
    ability: "heal_on_kill",
    effect: "狩人の弓",
    about: "倒すと回復",
    trail: "pve:trail_hunter",
    trailSound: "pve.trail.hunter",
    abilitySound: "pve.ability.hunter",
  },
  {
    item: "pve:bow_picker",
    label: "拾い屋の弓",
    rarity: "uncommon",
    base: 50,
    ability: "more_drops",
    effect: "拾い屋の弓",
    about: "落とし物が増える",
    trail: "pve:trail_picker",
    trailSound: "pve.trail.picker",
    abilitySound: "pve.ability.picker",
  },
  {
    item: "pve:bow_guardian",
    label: "守護者の弓",
    rarity: "rare",
    base: 60,
    ability: "guardian",
    effect: "守護者の弓",
    about: "背後の射手が、近い敵へ自動で撃つ",
    trail: "pve:trail_guardian",
    trailSound: "pve.trail.guardian",
    abilitySound: "pve.ability.guardian",
  },
  {
    item: "pve:bow_plain",
    label: "無銘弓",
    rarity: "rare",
    base: 70,
    ability: "none",
    trail: "pve:trail_plain",
    trailSound: "pve.trail.plain",
  },
  {
    item: "pve:bow_burst",
    label: "炸裂弓",
    rarity: "rare",
    base: 60,
    ability: "explode_small",
    effect: "炸裂弓",
    about: "当たった所で小爆発（20）",
    trail: "pve:trail_burst",
    trailSound: "pve.trail.burst",
    abilitySound: "pve.ability.burst",
  },
  {
    item: "pve:bow_lance",
    label: "光槍",
    rarity: "rare",
    base: 55,
    ability: "pierce_all",
    effect: "光槍",
    about: "並んだ敵を全部貫く（1 体ごとに −15%）",
    trail: "pve:trail_lance",
    trailSound: "pve.trail.lance",
    abilitySound: "pve.ability.lance",
  },
  {
    item: "pve:bow_billiard",
    label: "ビリヤード",
    rarity: "rare",
    base: 55,
    ability: "bounce",
    effect: "ビリヤード",
    about: "壁で 3 回跳ねる。跳ねるほど +50%",
    trail: "pve:trail_billiard",
    trailSound: "pve.trail.billiard",
    abilitySound: "pve.ability.billiard",
  },
  {
    item: "pve:bow_firework",
    label: "花火弓",
    rarity: "rare",
    base: 55,
    ability: "firework",
    effect: "花火弓",
    about: "着弾で花火。破片が飛ぶ",
    trail: "pve:trail_firework",
    trailSound: "pve.trail.firework",
    abilitySound: "pve.ability.firework",
  },
  {
    item: "pve:bow_gravity",
    label: "重力錘",
    rarity: "rare",
    base: 55,
    ability: "slam_down",
    effect: "重力錘",
    about: "敵を地面へ叩きつける",
    trail: "pve:trail_gravity",
    trailSound: "pve.trail.gravity",
    abilitySound: "pve.ability.gravity",
  },
  {
    item: "pve:bow_blood",
    label: "血の弓",
    rarity: "rare",
    base: 60,
    ability: "lifesteal",
    effect: "血の弓",
    about: "与えたダメージの 5% を回復",
    trail: "pve:trail_blood",
    trailSound: "pve.trail.blood",
    abilitySound: "pve.ability.blood",
  },
  {
    item: "pve:bow_railgun",
    label: "レールガン",
    rarity: "rare",
    base: 60,
    fullTicks: 24,
    ability: "railgun",
    effect: "レールガン",
    about: "溜め切ると極太のビーム（貫通）",
    trail: "pve:trail_railgun",
    trailSound: "pve.trail.railgun",
    abilitySound: "pve.ability.railgun",
  },
  {
    item: "pve:bow_spider",
    label: "蜘蛛の弓",
    rarity: "rare",
    base: 55,
    ability: "web",
    effect: "蜘蛛の弓",
    about: "当てた敵から糸。近くの敵を巻き込む",
    trail: "pve:trail_spider",
    trailSound: "pve.trail.spider",
    abilitySound: "pve.ability.spider",
  },
  {
    item: "pve:bow_mine",
    label: "地雷矢",
    rarity: "rare",
    base: 55,
    ability: "mine",
    effect: "地雷矢",
    about: "地面に刺さると杭。踏むと爆発",
    trail: "pve:trail_mine",
    trailSound: "pve.trail.mine",
    abilitySound: "pve.ability.mine",
  },
  {
    item: "pve:bow_twin",
    label: "双龍弓",
    rarity: "rare",
    base: 50,
    ability: "twin_spiral",
    effect: "双龍弓",
    about: "2 本が螺旋を描く（各 60%）",
    trail: "pve:trail_twin",
    trailSound: "pve.trail.twin",
    abilitySound: "pve.ability.twin",
  },
  {
    item: "pve:bow_holy",
    label: "聖水弓",
    rarity: "rare",
    base: 55,
    ability: "light_pillar",
    effect: "聖水弓",
    about: "着弾点に光の柱。中の敵が削れる",
    trail: "pve:trail_holy",
    trailSound: "pve.trail.holy",
    abilitySound: "pve.ability.holy",
  },
  {
    item: "pve:bow_brand",
    label: "烙印弓",
    rarity: "rare",
    base: 55,
    ability: "brand",
    effect: "烙印弓",
    about: "印を付ける。印の敵を倒すと爆散",
    trail: "pve:trail_brand",
    trailSound: "pve.trail.brand",
    abilitySound: "pve.ability.brand",
  },
  {
    item: "pve:bow_dice",
    label: "賽の弓",
    rarity: "rare",
    base: 60,
    ability: "dice",
    effect: "賽の弓",
    about: "命中ごとに 1〜6 倍（平均は同じ）",
    trail: "pve:trail_dice",
    trailSound: "pve.trail.dice",
    abilitySound: "pve.ability.dice",
  },
  {
    item: "pve:bow_card",
    label: "札の弓",
    rarity: "rare",
    base: 60,
    ability: "cards",
    effect: "札の弓",
    about: "3 枚のカードを順に撃つ",
    trail: "pve:trail_card",
    trailSound: "pve.trail.card",
    abilitySound: "pve.ability.card",
  },
  {
    item: "pve:bow_cannon",
    label: "大砲弓",
    rarity: "rare",
    base: 62,
    fullTicks: 30,
    ability: "cannon",
    effect: "大砲弓",
    about: "溜め切ってしか撃てない（1.5 秒・1.5 倍）。着弾で大爆発",
    trail: "pve:trail_cannon",
    trailSound: "pve.trail.cannon",
    abilitySound: "pve.ability.cannon",
  },
  {
    item: "pve:bow_harpoon",
    label: "ハープーンボウ",
    rarity: "legendary",
    base: 40,
    ability: "spread5",
    effect: "ハープーンボウ",
    about: "5 本に散らす（各 40%）",
    trail: "pve:trail_harpoon",
    trailSound: "pve.trail.harpoon",
    abilitySound: "pve.ability.harpoon",
  },
  {
    item: "pve:bow_pierce",
    label: "貫き",
    rarity: "legendary",
    base: 60,
    ability: "pierce_line",
    effect: "貫き",
    about: "後ろの敵へ貫通（−20%・最大数あり）",
    trail: "pve:trail_pierce",
    trailSound: "pve.trail.pierce",
    abilitySound: "pve.ability.pierce",
  },
  {
    item: "pve:bow_named",
    label: "銘入りの弓",
    rarity: "legendary",
    base: 60,
    ability: "enchant_luck",
    effect: "銘入りの弓",
    about: "エンチャントが付きやすい",
    trail: "pve:trail_named",
    trailSound: "pve.trail.named",
    abilitySound: "pve.ability.named",
  },
  {
    item: "pve:bow_stardust",
    label: "星屑",
    rarity: "legendary",
    base: 45,
    ability: "starfall",
    effect: "星屑",
    about: "着弾地点に星が降る（落ちるたびに削る）",
    trail: "pve:trail_stardust",
    spark: "pve:trail_star_spark",
    trailSound: "pve.trail.stardust",
    abilitySound: "pve.ability.stardust",
  },
  {
    item: "pve:bow_clock",
    label: "時詠み",
    rarity: "legendary",
    base: 60,
    ability: "time_stop",
    effect: "時詠み",
    about: "当てた敵の時間が止まる（短時間）",
    trail: "pve:trail_clock",
    trailSound: "pve.trail.clock",
    abilitySound: "pve.ability.clock",
  },
  {
    item: "pve:bow_pin",
    label: "影縫い",
    rarity: "legendary",
    base: 60,
    ability: "root",
    effect: "影縫い",
    about: "その場に縫い止める",
    trail: "pve:trail_pin",
    trailSound: "pve.trail.pin",
    abilitySound: "pve.ability.pin",
  },
  {
    item: "pve:bow_echo",
    label: "残響",
    rarity: "legendary",
    base: 35,
    ability: "echo",
    effect: "残響",
    about: "0.3 秒後、同じ場所にもう 1 発",
    trail: "pve:trail_echo",
    trailSound: "pve.trail.echo",
    abilitySound: "pve.ability.echo",
  },
  {
    item: "pve:bow_ward",
    label: "結界弓",
    rarity: "legendary",
    base: 50,
    ability: "ward",
    effect: "結界弓",
    about: "刺さった所に陣。陣の上で撃つと矢が 3 本",
    trail: "pve:trail_ward",
    trailSound: "pve.trail.ward",
    abilitySound: "pve.ability.ward",
  },
  {
    item: "pve:bow_missile",
    label: "追尾ミサイル",
    rarity: "legendary",
    base: 60,
    ability: "homing",
    effect: "追尾ミサイル",
    about: "曲がって追う（−20%）",
    trail: "pve:trail_missile",
    trailSound: "pve.trail.missile",
    abilitySound: "pve.ability.missile",
  },
  {
    item: "pve:bow_reverb",
    label: "反響弓",
    rarity: "legendary",
    base: 55,
    ability: "kill_echo",
    effect: "反響弓",
    about: "倒すと、その位置からもう 1 発",
    trail: "pve:trail_reverb",
    trailSound: "pve.trail.reverb",
    abilitySound: "pve.ability.reverb",
  },
  {
    item: "pve:bow_meteor",
    label: "流星",
    rarity: "legendary",
    base: 45,
    ability: "meteor",
    effect: "流星",
    about: "溜め切ると空から隕石。広く吹き飛ばす",
    trail: "pve:trail_meteor",
    trailSound: "pve.trail.meteor",
    abilitySound: "pve.ability.meteor",
  },
  {
    item: "pve:bow_return",
    label: "回旋",
    rarity: "legendary",
    base: 35,
    ability: "boomerang",
    effect: "回旋",
    about: "矢が戻ってくる（往復 2 ヒット）",
    trail: "pve:trail_return",
    trailSound: "pve.trail.return",
    abilitySound: "pve.ability.return",
  },
  {
    item: "pve:bow_hook",
    label: "鉤縄",
    rarity: "legendary",
    base: 60,
    ability: "pull",
    effect: "鉤縄",
    about: "当てた敵を引き寄せる",
    trail: "pve:trail_hook",
    trailSound: "pve.trail.hook",
    abilitySound: "pve.ability.hook",
  },
  {
    item: "pve:bow_combo",
    label: "連撃の証",
    rarity: "legendary",
    base: 40,
    ability: "combo",
    effect: "連撃の証",
    about: "当てるほど +10%（最大 +100%・外すとリセット）",
    trail: "pve:trail_combo",
    trailSound: "pve.trail.combo",
    abilitySound: "pve.ability.combo",
  },
  {
    item: "pve:bow_shadow",
    label: "影武者",
    rarity: "legendary",
    base: 35,
    ability: "shadow_shot",
    effect: "影武者",
    about: "分身が 0.2 秒後に同じ矢を撃つ",
    trail: "pve:trail_shadow",
    trailSound: "pve.trail.shadow",
    abilitySound: "pve.ability.shadow",
  },
  {
    item: "pve:bow_quiver",
    label: "無限矢筒",
    rarity: "legendary",
    base: 30,
    ability: "quiver",
    effect: "無限矢筒",
    about: "当てるたび矢が 1 本増える（最大 3 本・−40%）",
    trail: "pve:trail_quiver",
    trailSound: "pve.trail.quiver",
    abilitySound: "pve.ability.quiver",
  },
  {
    item: "pve:bow_dual",
    label: "双属の弓",
    rarity: "legendary",
    base: 55,
    ability: "dual_element",
    effect: "双属の弓",
    about: "属性が必ず 2 つ付く",
    trail: "pve:trail_dual",
    trailSound: "pve.trail.dual",
    abilitySound: "pve.ability.dual",
  },
  {
    item: "pve:bow_blackhole",
    label: "黒穴弓",
    rarity: "legendary",
    base: 55,
    ability: "blackhole",
    effect: "黒穴弓",
    about: "着弾点に黒い球。吸いながら削る",
    trail: "pve:trail_blackhole",
    trailSound: "pve.trail.blackhole",
    abilitySound: "pve.ability.blackhole",
  },
  {
    item: "pve:bow_aurora",
    label: "極光",
    rarity: "legendary",
    base: 55,
    ability: "aurora",
    effect: "極光",
    about: "着弾点に光のカーテン（範囲・持続）",
    trail: "pve:trail_aurora",
    trailSound: "pve.trail.aurora",
    abilitySound: "pve.ability.aurora",
  },
];
