/**
 * 軍団（★ごとのまとまり）。**いまは仮**（`docs/spec/16-enemy.md` 2 章）。
 *
 * > ### **本番はコンセプトごとに組み直す**（2026-09-10）
 * >
 * > **敵がほぼ揃ったので、確認用に 50 個をランダムに近い形で組んだ。**
 * > **守っているのは 3 つだけ**——**★の帯・6 種類まで・確率で引く。**
 * > **前の `zombie` / `skeleton` / `creeper` / `mock1`〜`mock11` は消した**
 * > （**中身が全部ゾンビだったので、確認に使えなくなった**）。
 *
 * **この表は `npm test` が見張る**（`tests/core.test.ts`）。
 */
import type { LegionDef } from "../enemy.js";

/** **何も選ばれていないときの相手**（★1・いちばん素直な群れ） */
export const DEFAULT_LEGION = "swarm";

export const LEGIONS: Readonly<Record<string, LegionDef>> = {
  // ---- ★1
  swarm: {
    id: "swarm",
    name: "群れ",
    star: 1,
    concept: "数で押される。避ける場所を作れるか",
    fixed: 28,
    perWave: 3,
    mix: [
      { enemy: "grunt", weight: 45 },
      { enemy: "silver", weight: 25 },
      { enemy: "slime", weight: 20 },
      { enemy: "bat", weight: 10 },
    ],
  },
  volley: {
    id: "volley",
    name: "射手隊",
    star: 1,
    concept: "遮蔽を使えるか。棒立ちが一番痛い",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "archer", weight: 60 },
      { enemy: "grunt", weight: 30 },
      { enemy: "sheep", weight: 10 },
    ],
  },
  vermin: {
    id: "vermin",
    name: "虫の巣",
    star: 1,
    concept: "小さくて速い。数を捌けるか",
    fixed: 28,
    perWave: 3,
    mix: [
      { enemy: "silver", weight: 55 },
      { enemy: "bat", weight: 30 },
      { enemy: "slime", weight: 15 },
    ],
  },
  pasture: {
    id: "pasture",
    name: "牧場",
    star: 1,
    concept: "1 体は弱い。数だけで押してくる",
    fixed: 32,
    perWave: 3,
    mix: [
      { enemy: "sheep", weight: 40 },
      { enemy: "grunt", weight: 30 },
      { enemy: "slime", weight: 20 },
      { enemy: "bat", weight: 10 },
    ],
  },
  slimepit: {
    id: "slimepit",
    name: "ぬかるみ",
    star: 1,
    concept: "跳ねて寄る。足を止められる",
    fixed: 24,
    perWave: 3,
    mix: [
      { enemy: "slime", weight: 60 },
      { enemy: "silver", weight: 25 },
      { enemy: "grunt", weight: 15 },
    ],
  },
  nightcave: {
    id: "nightcave",
    name: "洞窟の夜",
    star: 1,
    concept: "空と地上の同時。視線が散る",
    fixed: 24,
    perWave: 3,
    mix: [
      { enemy: "bat", weight: 45 },
      { enemy: "archer", weight: 35 },
      { enemy: "silver", weight: 20 },
    ],
  },
  motley: {
    id: "motley",
    name: "寄せ集め",
    star: 1,
    concept: "★1 の顔見せ。全部が少しずつ来る",
    fixed: 28,
    perWave: 3,
    mix: [
      { enemy: "grunt", weight: 30 },
      { enemy: "archer", weight: 25 },
      { enemy: "silver", weight: 20 },
      { enemy: "slime", weight: 15 },
      { enemy: "bat", weight: 10 },
    ],
  },
  frontline: {
    id: "frontline",
    name: "前線",
    star: 1,
    concept: "正面から殴り合う。基本の形",
    fixed: 24,
    perWave: 3,
    mix: [
      { enemy: "grunt", weight: 70 },
      { enemy: "archer", weight: 30 },
    ],
  },
  // ---- ★2
  shield: {
    id: "shield",
    name: "衛兵隊",
    star: 2,
    concept: "硬い前衛の裏から矢が来る。前を割れるか",
    fixed: 24,
    perWave: 3,
    mix: [
      { enemy: "zguard", weight: 35 },
      { enemy: "sbowman", weight: 30 },
      { enemy: "grunt", weight: 20 },
      { enemy: "archer", weight: 15 },
    ],
  },
  blast: {
    id: "blast",
    name: "爆撃隊",
    star: 2,
    concept: "足元が危ない。立ち位置を動かし続けられるか",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "bomblet", weight: 30 },
      { enemy: "slinger", weight: 30 },
      { enemy: "gast", weight: 15 },
      { enemy: "crusher", weight: 15 },
      { enemy: "grunt", weight: 10 },
    ],
  },
  blade: {
    id: "blade",
    name: "刃の群れ",
    star: 2,
    concept: "近づかれたら削られる。間合いを保てるか",
    fixed: 24,
    perWave: 3,
    mix: [
      { enemy: "sawman", weight: 30 },
      { enemy: "spinner", weight: 25 },
      { enemy: "chiller", weight: 20 },
      { enemy: "zguard", weight: 15 },
      { enemy: "grunt", weight: 10 },
    ],
  },
  frost: {
    id: "frost",
    name: "凍える隊",
    star: 2,
    concept: "鈍足を撒かれる。逃げ足を奪われる",
    fixed: 24,
    perWave: 3,
    mix: [
      { enemy: "chiller", weight: 45 },
      { enemy: "zguard", weight: 25 },
      { enemy: "sbowman", weight: 20 },
      { enemy: "slime", weight: 10 },
    ],
  },
  stoning: {
    id: "stoning",
    name: "投石隊",
    star: 2,
    concept: "遠くから重い石。遮蔽の使い方を問う",
    fixed: 22,
    perWave: 3,
    mix: [
      { enemy: "slinger", weight: 45 },
      { enemy: "sbowman", weight: 25 },
      { enemy: "zguard", weight: 20 },
      { enemy: "grunt", weight: 10 },
    ],
  },
  skyfire: {
    id: "skyfire",
    name: "空爆",
    star: 2,
    concept: "上から火の玉。地上戦の型が崩れる",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "gast", weight: 40 },
      { enemy: "sbowman", weight: 25 },
      { enemy: "bat", weight: 20 },
      { enemy: "archer", weight: 15 },
    ],
  },
  heavy: {
    id: "heavy",
    name: "重撃隊",
    star: 2,
    concept: "一発が重い。受けずに捌けるか",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "crusher", weight: 40 },
      { enemy: "zguard", weight: 30 },
      { enemy: "cow", weight: 20 },
      { enemy: "grunt", weight: 10 },
    ],
  },
  stampede: {
    id: "stampede",
    name: "暴走",
    star: 2,
    concept: "押し寄せる質量。逃げ道が塞がる",
    fixed: 28,
    perWave: 3,
    mix: [
      { enemy: "cow", weight: 45 },
      { enemy: "sheep", weight: 25 },
      { enemy: "grunt", weight: 20 },
      { enemy: "silver", weight: 10 },
    ],
  },
  sawmill: {
    id: "sawmill",
    name: "製材所",
    star: 2,
    concept: "回る刃だらけ。密集すると溶ける",
    fixed: 22,
    perWave: 3,
    mix: [
      { enemy: "sawman", weight: 40 },
      { enemy: "spinner", weight: 30 },
      { enemy: "crusher", weight: 20 },
      { enemy: "grunt", weight: 10 },
    ],
  },
  bombline: {
    id: "bombline",
    name: "爆弾線",
    star: 2,
    concept: "爆風で陣形を崩される",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "bomblet", weight: 40 },
      { enemy: "slinger", weight: 25 },
      { enemy: "zguard", weight: 20 },
      { enemy: "gast", weight: 15 },
    ],
  },
  // ---- ★3
  banner: {
    id: "banner",
    name: "近衛隊",
    star: 3,
    concept: "回復と鼓舞が付く。支援から先に潰せるか",
    fixed: 24,
    perWave: 3,
    mix: [
      { enemy: "zroyal", weight: 30 },
      { enemy: "sroyal", weight: 20 },
      { enemy: "healer", weight: 15 },
      { enemy: "rouser", weight: 15 },
      { enemy: "grunt", weight: 20 },
    ],
  },
  venomous: {
    id: "venomous",
    name: "毒火隊",
    star: 3,
    concept: "持続ダメージ。立ち止まると溶ける",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "venom", weight: 25 },
      { enemy: "blaze", weight: 25 },
      { enemy: "boneman", weight: 20 },
      { enemy: "bomber", weight: 15 },
      { enemy: "archer", weight: 15 },
    ],
  },
  sky: {
    id: "sky",
    name: "空襲",
    star: 3,
    concept: "上から来る。近接だけでは届かない",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "flyer", weight: 35 },
      { enemy: "gast", weight: 20 },
      { enemy: "blaze", weight: 20 },
      { enemy: "bat", weight: 15 },
      { enemy: "archer", weight: 10 },
    ],
  },
  siege: {
    id: "siege",
    name: "重装隊",
    star: 3,
    concept: "硬い。手数と時間を要求される",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "tank", weight: 30 },
      { enemy: "bigslime", weight: 25 },
      { enemy: "zroyal", weight: 25 },
      { enemy: "healer", weight: 20 },
    ],
  },
  outlaw: {
    id: "outlaw",
    name: "無法者",
    star: 3,
    concept: "撃ってくる相手ばかり。詰め方を問う",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "gunner", weight: 35 },
      { enemy: "slinger", weight: 25 },
      { enemy: "sroyal", weight: 20 },
      { enemy: "bomber", weight: 20 },
    ],
  },
  inferno: {
    id: "inferno",
    name: "業火",
    star: 3,
    concept: "火と爆発。地面が安全でなくなる",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "blaze", weight: 40 },
      { enemy: "bomber", weight: 25 },
      { enemy: "venom", weight: 20 },
      { enemy: "gast", weight: 15 },
    ],
  },
  ossuary: {
    id: "ossuary",
    name: "納骨堂",
    star: 3,
    concept: "骨だらけ。遠近の両方から来る",
    fixed: 22,
    perWave: 3,
    mix: [
      { enemy: "boneman", weight: 35 },
      { enemy: "sroyal", weight: 25 },
      { enemy: "sbowman", weight: 25 },
      { enemy: "archer", weight: 15 },
    ],
  },
  support: {
    id: "support",
    name: "支援隊",
    star: 3,
    concept: "倒しても回復される。順番を間違えると終わらない",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "healer", weight: 25 },
      { enemy: "rouser", weight: 25 },
      { enemy: "zroyal", weight: 30 },
      { enemy: "sroyal", weight: 20 },
    ],
  },
  splitter: {
    id: "splitter",
    name: "分裂体",
    star: 3,
    concept: "倒すと増える。数が減らない焦り",
    fixed: 22,
    perWave: 3,
    mix: [
      { enemy: "bigslime", weight: 40 },
      { enemy: "slime", weight: 30 },
      { enemy: "silver", weight: 20 },
      { enemy: "tank", weight: 10 },
    ],
  },
  airraid: {
    id: "airraid",
    name: "制空",
    star: 3,
    concept: "空を取られる。落とす手段が要る",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "flyer", weight: 40 },
      { enemy: "blaze", weight: 25 },
      { enemy: "gast", weight: 20 },
      { enemy: "sbowman", weight: 15 },
    ],
  },
  demoteam: {
    id: "demoteam",
    name: "爆破班",
    star: 3,
    concept: "投げ込まれる爆弾。予告円を読めるか",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "bomber", weight: 35 },
      { enemy: "bomblet", weight: 25 },
      { enemy: "slinger", weight: 20 },
      { enemy: "zroyal", weight: 20 },
    ],
  },
  royalguard: {
    id: "royalguard",
    name: "王の盾",
    star: 3,
    concept: "硬い前衛 ＋ 回復。攻めの総量を試される",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "zroyal", weight: 35 },
      { enemy: "tank", weight: 25 },
      { enemy: "sroyal", weight: 20 },
      { enemy: "healer", weight: 20 },
    ],
  },
  // ---- ★4
  demolition: {
    id: "demolition",
    name: "爆破部隊",
    star: 4,
    concept: "爆発しかいない。距離を取り続けられるか",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "creeper", weight: 30 },
      { enemy: "bomblet", weight: 25 },
      { enemy: "charged", weight: 20 },
      { enemy: "taint", weight: 15 },
      { enemy: "zknight", weight: 10 },
    ],
  },
  marksman: {
    id: "marksman",
    name: "狙撃隊",
    star: 4,
    concept: "遠距離が主体。詰めるまでに削られる",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "shotgun", weight: 25 },
      { enemy: "gunner", weight: 25 },
      { enemy: "sknight", weight: 25 },
      { enemy: "sbowman", weight: 15 },
      { enemy: "archer", weight: 10 },
    ],
  },
  elite: {
    id: "elite",
    name: "精鋭隊",
    star: 4,
    concept: "一発が重い。事故で落ちる",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "zknight", weight: 30 },
      { enemy: "sknight", weight: 20 },
      { enemy: "crit", weight: 15 },
      { enemy: "blinker", weight: 15 },
      { enemy: "mite", weight: 10 },
      { enemy: "tank", weight: 10 },
    ],
  },
  phantom: {
    id: "phantom",
    name: "亡霊",
    star: 4,
    concept: "壁を抜けて来る。籠もれない",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "wraith", weight: 35 },
      { enemy: "blinker", weight: 25 },
      { enemy: "mite", weight: 20 },
      { enemy: "bat", weight: 20 },
    ],
  },
  plague: {
    id: "plague",
    name: "汚染地帯",
    star: 4,
    concept: "床が毒になる。居場所を奪われる",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "taint", weight: 30 },
      { enemy: "venom", weight: 25 },
      { enemy: "creeper", weight: 20 },
      { enemy: "zknight", weight: 15 },
      { enemy: "boneman", weight: 10 },
    ],
  },
  knightorder: {
    id: "knightorder",
    name: "騎士団",
    star: 4,
    concept: "硬くて強い。正攻法で殴り合う",
    fixed: 20,
    perWave: 3,
    mix: [
      { enemy: "zknight", weight: 40 },
      { enemy: "sknight", weight: 25 },
      { enemy: "zroyal", weight: 20 },
      { enemy: "healer", weight: 15 },
    ],
  },
  ambush: {
    id: "ambush",
    name: "奇襲",
    star: 4,
    concept: "跳んで背後を取る。囲まれる",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "blinker", weight: 30 },
      { enemy: "mite", weight: 25 },
      { enemy: "crit", weight: 20 },
      { enemy: "wraith", weight: 15 },
      { enemy: "silver", weight: 10 },
    ],
  },
  buckshot: {
    id: "buckshot",
    name: "散弾陣",
    star: 4,
    concept: "面で撃たれる。横に避けられるか",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "shotgun", weight: 35 },
      { enemy: "gunner", weight: 25 },
      { enemy: "sknight", weight: 25 },
      { enemy: "sbowman", weight: 15 },
    ],
  },
  thunder: {
    id: "thunder",
    name: "帯電群",
    star: 4,
    concept: "死に際に雷。倒し方まで考える",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "charged", weight: 35 },
      { enemy: "creeper", weight: 25 },
      { enemy: "chiller", weight: 20 },
      { enemy: "zknight", weight: 20 },
    ],
  },
  assassin: {
    id: "assassin",
    name: "暗殺者",
    star: 4,
    concept: "当たると大きい。被弾 1 回が重い",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "crit", weight: 35 },
      { enemy: "blinker", weight: 25 },
      { enemy: "mite", weight: 20 },
      { enemy: "wraith", weight: 20 },
    ],
  },
  // ---- ★5
  general: {
    id: "general",
    name: "将軍の隊",
    star: 5,
    concept: "総合力。支援付きの精鋭",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "zgeneral", weight: 25 },
      { enemy: "sgeneral", weight: 20 },
      { enemy: "zknight", weight: 20 },
      { enemy: "sknight", weight: 15 },
      { enemy: "golem", weight: 10 },
      { enemy: "rouser", weight: 10 },
    ],
  },
  danmaku: {
    id: "danmaku",
    name: "弾幕陣",
    star: 5,
    concept: "画面が弾で埋まる。避け続けられるか",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "barrage", weight: 25 },
      { enemy: "seeker", weight: 20 },
      { enemy: "chamber", weight: 15 },
      { enemy: "kitsune", weight: 15 },
      { enemy: "gunner", weight: 15 },
      { enemy: "blaze", weight: 10 },
    ],
  },
  doom: {
    id: "doom",
    name: "終末",
    star: 5,
    concept: "全部が爆発する。逃げ場が消える",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "titan", weight: 20 },
      { enemy: "vital", weight: 20 },
      { enemy: "boltcreeper", weight: 20 },
      { enemy: "charged", weight: 20 },
      { enemy: "creeper", weight: 20 },
    ],
  },
  ironwall: {
    id: "ironwall",
    name: "鉄壁",
    star: 5,
    concept: "削り切れるか。時間との戦い",
    fixed: 14,
    perWave: 3,
    mix: [
      { enemy: "golem", weight: 30 },
      { enemy: "titan", weight: 25 },
      { enemy: "tank", weight: 25 },
      { enemy: "healer", weight: 20 },
    ],
  },
  foxfire: {
    id: "foxfire",
    name: "狐火",
    star: 5,
    concept: "広い範囲へ炎。前に出られない",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "kitsune", weight: 35 },
      { enemy: "blaze", weight: 25 },
      { enemy: "venom", weight: 20 },
      { enemy: "flyer", weight: 20 },
    ],
  },
  longshot: {
    id: "longshot",
    name: "狙撃班",
    star: 5,
    concept: "50 マス先から撃たれる。近づく前に削られる",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "chamber", weight: 30 },
      { enemy: "sgeneral", weight: 25 },
      { enemy: "shotgun", weight: 25 },
      { enemy: "gunner", weight: 20 },
    ],
  },
  vitalpoint: {
    id: "vitalpoint",
    name: "急所隊",
    star: 5,
    concept: "割合ダメージ。HP を上げても軽くならない",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "vital", weight: 30 },
      { enemy: "crit", weight: 25 },
      { enemy: "mite", weight: 25 },
      { enemy: "blinker", weight: 20 },
    ],
  },
  blastwave: {
    id: "blastwave",
    name: "大爆発",
    star: 5,
    concept: "半径 8 の爆発。1 発で陣形が消える",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "boltcreeper", weight: 30 },
      { enemy: "creeper", weight: 25 },
      { enemy: "charged", weight: 25 },
      { enemy: "bomber", weight: 20 },
    ],
  },
  homingfire: {
    id: "homingfire",
    name: "追尾",
    star: 5,
    concept: "曲がって追ってくる弾。障害物を使えるか",
    fixed: 16,
    perWave: 3,
    mix: [
      { enemy: "seeker", weight: 35 },
      { enemy: "barrage", weight: 25 },
      { enemy: "flyer", weight: 20 },
      { enemy: "sroyal", weight: 20 },
    ],
  },
  warhost: {
    id: "warhost",
    name: "総軍",
    star: 5,
    concept: "★5 の総出。いまの上限",
    fixed: 18,
    perWave: 3,
    mix: [
      { enemy: "zgeneral", weight: 20 },
      { enemy: "sgeneral", weight: 20 },
      { enemy: "golem", weight: 15 },
      { enemy: "titan", weight: 15 },
      { enemy: "barrage", weight: 15 },
      { enemy: "healer", weight: 15 },
    ],
  },
};
